import { StyleSheet } from "react-native";

export const fridgeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  scrollContainer: {
    flexGrow: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 2,
    borderColor: "#e1f5fe",
  },
  logo: {
    width: 55,
    height: 55,
    resizeMode: "contain",
  },
  greetingSection: {
    paddingHorizontal: 20,
    paddingVertical: 25,
  },
  greeting: {
    fontSize: 20,
    fontWeight: "500",
    color: "#64748b",
    marginBottom: 5,
  },
  username: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1e293b",
    letterSpacing: -0.5,
  },
  searchContainer: {
    marginHorizontal: 20,
    marginBottom: 25,
    backgroundColor: "#ffffff",
    borderRadius: 15,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2.22,
    elevation: 3,
  },
  searchInput: {
    height: 50,
    fontSize: 16,
    color: "#374151",
  },
  fridgeSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  fridgeIcon: {
    width: 28,
    height: 28,
    marginRight: 10,
    tintColor: "#059669",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1e293b",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: "#64748b",
    marginBottom: 20,
  },
  itemsCarousel: {
    paddingLeft: 20,
  },
  itemCard: {
    width: 120,
    marginRight: 15,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 3.84,
    elevation: 5,
  },
  itemImage: {
    width: 60,
    height: 60,
    resizeMode: "contain",
    marginBottom: 10,
  },
  statusRow: {
    flexDirection: "column",
    alignItems: "center",
  },
  statusIconContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 5,
  },
  statusIcon: {
    width: 16,
    height: 16,
    marginRight: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
  },
  itemName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1e293b",
    textAlign: "center",
    marginTop: 5,
  },
  homeQuantityControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 8,
  },
  homeQuantityButton: {
    backgroundColor: "#059669",
    borderRadius: 6,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  homeQuantityButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  homeQuantityDisplay: {
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  homeQuantityText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#475569",
  },
  quantityInput: {
    fontSize: 12,
    fontWeight: "700",
    color: "#475569",
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#059669",
    backgroundColor: "#ffffff",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    marginBottom: 15,
    opacity: 0.5,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#64748b",
    textAlign: "center",
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 20,
  },
  addButton: {
    marginHorizontal: 20,
    marginBottom: 30,
    backgroundColor: "#059669",
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
    shadowColor: "#059669",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  addButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
});

export const fridgeItemsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  scrollContainer: {
    flexGrow: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 2,
    borderColor: "#e1f5fe",
  },
  titleSection: {
    paddingHorizontal: 20,
    paddingVertical: 25,
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: "#1e293b",
    letterSpacing: -0.5,
  },
  searchContainer: {
    marginHorizontal: 20,
    marginBottom: 25,
    backgroundColor: "#ffffff",
    borderRadius: 15,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2.22,
    elevation: 3,
  },
  searchInput: {
    height: 50,
    fontSize: 16,
    color: "#374151",
  },
  labelContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  itemsLabel: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e293b",
  },
  filterText: {
    fontSize: 16,
    color: "#059669",
    fontWeight: "600",
  },
  itemsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  itemCard: {
    width: "47%",
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4.65,
    elevation: 6,
  },
  itemImage: {
    width: 70,
    height: 70,
    resizeMode: "contain",
    marginBottom: 12,
  },
  itemText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1e293b",
    textAlign: "center",
  },
  addButton: {
    marginHorizontal: 20,
    marginBottom: 30,
    backgroundColor: "#059669",
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
    shadowColor: "#059669",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  addButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
});
export const fridgeCategoryStyles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#f8fafc" 
  },
  scrollContainer: {
    flexGrow: 1,
  },
  header: { 
    flexDirection: "row", 
    alignItems: "center", 
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  avatar: { 
    width: 45, 
    height: 45, 
    borderRadius: 22.5,
    borderWidth: 2,
    borderColor: "#e1f5fe",
  },
  titleSection: {
    paddingHorizontal: 20,
    paddingVertical: 25,
  },
  title: { 
    fontSize: 32, 
    fontWeight: "700", 
    color: "#1e293b",
    letterSpacing: -0.5,
  },
  searchContainer: {
    marginHorizontal: 20,
    marginBottom: 25,
    backgroundColor: "#ffffff",
    borderRadius: 15,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2.22,
    elevation: 3,
  },
  searchInput: { 
    height: 50, 
    fontSize: 16,
    color: "#374151",
  },
  labelContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sectionLabel: { 
    fontSize: 20, 
    fontWeight: "700",
    color: "#1e293b",
  },
  filterText: { 
    fontSize: 16, 
    color: "#059669",
    fontWeight: "600",
  },
  itemsList: {
    paddingHorizontal: 20,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 3.84,
    elevation: 3,
  },
  itemImage: { 
    width: 55, 
    height: 55, 
    resizeMode: "contain",
    marginRight: 15,
  },
  info: { 
    flex: 1,
  },
  statusRow: { 
    flexDirection: "row", 
    alignItems: "center",
    marginBottom: 8,
  },
  statusIcon: { 
    width: 20, 
    height: 20, 
    marginRight: 6 
  },
  statusText: { 
    fontSize: 14, 
    color: "#64748b",
    fontWeight: "500",
  },
  itemName: { 
    fontSize: 18, 
    fontWeight: "600", 
    color: "#1e293b",
  },
  countContainer: {
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 40,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  quantityInput: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
    textAlign: "center",
    borderColor: "#059669",
    backgroundColor: "#ffffff",
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  quantityButton: {
    backgroundColor: "#059669",
    borderRadius: 8,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#059669",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  quantityButtonDisabled: {
    backgroundColor: "#94a3b8",
    shadowColor: "#94a3b8",
  },
  quantityButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  itemCount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#475569",
  },
  separator: { 
    height: 1, 
    backgroundColor: "#e2e8f0",
    marginVertical: 8,
  },
  addButton: {
    marginHorizontal: 20,
    marginVertical: 30,
    backgroundColor: "#059669",
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
    shadowColor: "#059669",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },  addButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    color: "#64748b",
    marginTop: 15,
    fontWeight: "500",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    marginBottom: 20,
    opacity: 0.5,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#64748b",
    textAlign: "center",
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 20,
  },
});
export const fridgeAddStyles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#f8fafc"
  },
  scrollContainer: {
    flexGrow: 1,
  },
  header: { 
    flexDirection: "row", 
    alignItems: "center", 
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  avatar: { 
    width: 45, 
    height: 45, 
    borderRadius: 22.5,
    borderWidth: 2,
    borderColor: "#e1f5fe",
  },
  titleSection: {
    paddingHorizontal: 20,
    paddingVertical: 25,
  },
  title: { 
    fontSize: 32, 
    fontWeight: "700", 
    color: "#1e293b",
    letterSpacing: -0.5,
  },
  formContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },  inputGroup: {
    marginBottom: 20,
    position: "relative",
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: "#374151",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2.22,
    elevation: 3,
  },
  addButton: {
    marginHorizontal: 20,
    marginBottom: 30,
    backgroundColor: "#059669",
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
    shadowColor: "#059669",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },  addButtonText: { 
    color: "#ffffff", 
    fontSize: 18, 
    fontWeight: "700",
    letterSpacing: 0.5,
  },  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownText: {
    fontSize: 16,
    color: "#374151",
  },
  placeholderText: {
    color: "#9ca3af",
  },  dropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    marginTop: 5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 5.84,
    elevation: 10,
    maxHeight: 200,
    zIndex: 9999,
  },dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },dropdownItemText: {
    fontSize: 16,
    color: "#374151",
  },  dropdownInput: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: "#374151",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2.22,
    elevation: 3,
  },  dropdownArrow: {
    fontSize: 12,
    color: "#9ca3af",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 20,
    maxHeight: "70%",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4.65,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 16,
    textAlign: "center",
  },
  modalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  selectedItem: {
    backgroundColor: "#f0f9ff",
  },  modalItemText: {
    fontSize: 16,
    color: "#374151",
  },
  modalItemSubtext: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 2,
  },
  selectedItemText: {
    color: "#0369a1",
    fontWeight: "600",
  },
  checkmark: {
    fontSize: 16,
    color: "#059669",
    fontWeight: "700",
  },
  clearButton: {
    marginTop: 8,
    alignSelf: "flex-end",
    paddingVertical: 4,
    paddingHorizontal: 12,
    backgroundColor: "#f87171",
    borderRadius: 6,
  },  clearButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  separatorContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
  },  separatorText: {
    fontSize: 14,
    color: "#94a3b8",
    fontWeight: "500",
  },  
  // Calendar Modal Styles
  calendarModalContent: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    maxHeight: "95%",
    minHeight: 500,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4.65,
    elevation: 8,
  },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  navButton: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    width: 45,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  navButtonText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#374151",
  },
  monthYearButton: {
    backgroundColor: "#059669",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    minWidth: 200,
    alignItems: "center",
  },
  monthYearText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
  },
  yearJump: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 15,
    marginBottom: 20,
  },
  yearButton: {
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  yearButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#64748b",
  },
  weekHeader: {
    flexDirection: "row",
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: "#e0f2fe",
  },
  weekDay: {
    flex: 1,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "700",
    color: "#059669",
    paddingVertical: 5,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 20,
  },
  emptyDay: {
    width: "14.28%",
    height: 45,
  },
  calendarDay: {
    width: "14.28%",
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginVertical: 2,
  },
  pastDay: {
    opacity: 0.3,
  },
  todayDay: {
    backgroundColor: "#e0f2fe",
    borderWidth: 2,
    borderColor: "#0891b2",
  },
  selectedDay: {
    backgroundColor: "#059669",
    borderWidth: 0,
  },
  calendarDayText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
  },
  pastDayText: {
    color: "#9ca3af",
  },
  todayDayText: {
    color: "#0891b2",
    fontWeight: "700",
  },  selectedDayText: {
    color: "#ffffff",
    fontWeight: "700",
  },
});